# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jpheckles/Documents/programming/Flight-Planner

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jpheckles/Documents/programming/Flight-Planner

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jpheckles/Documents/programming/Flight-Planner/CMakeFiles /home/jpheckles/Documents/programming/Flight-Planner//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jpheckles/Documents/programming/Flight-Planner/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FlightPlanner

# Build rule for target.
FlightPlanner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FlightPlanner
.PHONY : FlightPlanner

# fast build rule for target.
FlightPlanner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlightPlanner.dir/build.make CMakeFiles/FlightPlanner.dir/build
.PHONY : FlightPlanner/fast

src/Driver.o: src/Driver.cpp.o
.PHONY : src/Driver.o

# target to build an object file
src/Driver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlightPlanner.dir/build.make CMakeFiles/FlightPlanner.dir/src/Driver.cpp.o
.PHONY : src/Driver.cpp.o

src/Driver.i: src/Driver.cpp.i
.PHONY : src/Driver.i

# target to preprocess a source file
src/Driver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlightPlanner.dir/build.make CMakeFiles/FlightPlanner.dir/src/Driver.cpp.i
.PHONY : src/Driver.cpp.i

src/Driver.s: src/Driver.cpp.s
.PHONY : src/Driver.s

# target to generate assembly for a file
src/Driver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlightPlanner.dir/build.make CMakeFiles/FlightPlanner.dir/src/Driver.cpp.s
.PHONY : src/Driver.cpp.s

src/JPString.o: src/JPString.cpp.o
.PHONY : src/JPString.o

# target to build an object file
src/JPString.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlightPlanner.dir/build.make CMakeFiles/FlightPlanner.dir/src/JPString.cpp.o
.PHONY : src/JPString.cpp.o

src/JPString.i: src/JPString.cpp.i
.PHONY : src/JPString.i

# target to preprocess a source file
src/JPString.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlightPlanner.dir/build.make CMakeFiles/FlightPlanner.dir/src/JPString.cpp.i
.PHONY : src/JPString.cpp.i

src/JPString.s: src/JPString.cpp.s
.PHONY : src/JPString.s

# target to generate assembly for a file
src/JPString.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlightPlanner.dir/build.make CMakeFiles/FlightPlanner.dir/src/JPString.cpp.s
.PHONY : src/JPString.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlightPlanner.dir/build.make CMakeFiles/FlightPlanner.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlightPlanner.dir/build.make CMakeFiles/FlightPlanner.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlightPlanner.dir/build.make CMakeFiles/FlightPlanner.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

test/test.o: test/test.cpp.o
.PHONY : test/test.o

# target to build an object file
test/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlightPlanner.dir/build.make CMakeFiles/FlightPlanner.dir/test/test.cpp.o
.PHONY : test/test.cpp.o

test/test.i: test/test.cpp.i
.PHONY : test/test.i

# target to preprocess a source file
test/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlightPlanner.dir/build.make CMakeFiles/FlightPlanner.dir/test/test.cpp.i
.PHONY : test/test.cpp.i

test/test.s: test/test.cpp.s
.PHONY : test/test.s

# target to generate assembly for a file
test/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlightPlanner.dir/build.make CMakeFiles/FlightPlanner.dir/test/test.cpp.s
.PHONY : test/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FlightPlanner"
	@echo "... src/Driver.o"
	@echo "... src/Driver.i"
	@echo "... src/Driver.s"
	@echo "... src/JPString.o"
	@echo "... src/JPString.i"
	@echo "... src/JPString.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

